const searchData = [
  { type: 'location', data: 'Khuvsgul lake', key: 1 },
  { type: 'location', data: 'Ulaanbaatar city', key: 2 },
  { type: 'location', data: 'Ulaanba', key: 3 },
  { type: 'location', data: 'Terelj goy gazar', key: 4 },
  { type: 'location', data: 'Bogdkhan Mountain', key: 5 },
  { type: 'location', data: 'Jargalantiin am', key: 6 },
  { type: 'location', data: 'Sugnuguriin river', key: 7 },
  { type: 'location', data: 'Ugii lake', key: 8 },
  { type: 'location', data: 'aaaa aa', key: 9 },
  { type: 'location', data: 'bbbb bb', key: 10 },
  { type: 'location', data: 'ccc cc', key: 11 },
  { type: 'location', data: 'ddd dd', key: 12 },
  { type: 'location', data: 'eeee ee', key: 13 },
  { type: 'location', data: 'fff fff', key: 14 },
  { type: 'location', data: 'ggg gggg', key: 15 },
  { type: 'location', data: 'hhh hhhh', key: 16 },
  { type: 'location', data: 'iii iiiiii', key: 17 },
  { type: 'location', data: 'jjj jjjjjjj', key: 18 },
  { type: 'location', data: 'kkk kkkkkkk', key: 19 },

  { type: 'hotel', data: 'Best Hotel', key: 20 },
  { type: 'hotel', data: 'City Hotel', key: 21 },
  { type: 'hotel', data: 'Continental Hotel', key: 22 },
  { type: 'hotel', data: 'Nomado Hotel', key: 23 },
  { type: 'hotel', data: 'Puma Hotel', key: 24 },
  { type: 'something else', data: 'Different type', key: 25 },
  { type: 'something else', data: 'Sukhbaatar district', key: 26 },
  { type: 'something else', data: '19-p xopooлол', key: 27 },
];

export default searchData;
