import './globals.css';
// import type { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: 'iHotel',
//   description: 'Generated by create next app',
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/favicon.png"></link>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        ></meta>
      </head>
      <body className="relative">{children}</body>
    </html>
  );
}
