declare namespace HotelData {
  interface full {
    activities: [];
    average: number;
    comfort: number;
    diff: number;
    employees: number;
    enddate: string;
    fresh: number;
    hasPage: number;
    hotel: Hotel;
    isClosed: number;
    location: number;
    offerHotels: hotel[];
    orderCount: number;
    path: string;
    phoneNumber: string;
    price: number;
    rate: string;
    reviews: [];
    rooms: roomData.room[];
    services: { activities: [] };
    specialServices: [];
    startdate: string;
    things: number;
  }
  interface Hotel {
    address: string;
    addressEn: string | null;
    ageChild: number;
    cancellationPolicies: string;
    checkInTime: string;
    checkOutTime: string;
    commonLocationIds: string;
    companyName: string;
    contact: string;
    contactEn: string | null;
    coverPhoto: string;
    createdAt: string;
    defaultLocale: string | null;
    description: string | null;
    districtId: number;
    email: string;
    emailBook: string | null;
    facilities: Facilities[];
    hasChatbot: boolean;
    hasGoal: number;
    hasIhotel: boolean;
    hasOnlineBook: boolean;
    hasTime: boolean;
    hasXroom: boolean;
    hotelCategoryId: number;
    hotelTypeId: number;
    id: number;
    image: string;
    images: string[];
    includedPrice: string | null;
    includedServiceMessage: string;
    introduction: string;
    introductionEn: string | null;
    isActive: boolean;
    isAutoArrange: boolean;
    isCheap: number;
    isCitypayer: boolean;
    isClosed: number | null;
    isInternet: number;
    isNew: boolean;
    isNewXroom: boolean;
    isOffline: number;
    isOnline: number;
    isPopularItrip: number;
    isRecommended: number;
    isShowBooking: number;
    isShowPayment: boolean;
    isShowRules: boolean;
    isTest: boolean;
    isTop: number;
    isVatpayer: boolean;
    lat: number;
    lng: number;
    location: { lat: string; lng: string };
    maxTime: number;
    name: string;
    nameEn: string | null;
    otherInfo: string;
    otherInfoEn: string | null;
    otherPhotos: string;
    otherService: string | null;
    otherServiceEn: string | null;
    phone: string;
    phoneBook: string | null;
    priority: number;
    provinceId: number;
    published: number;
    rating: number;
    registerNo: string;
    registeredAtXroom: number | null;
    resEmail: string;
    resPhone: string;
    reservations: Reservations[];
    roomNumber: number;
    roomTypes: RoomTypes[];
    services: [];
    shortAddress: string | null;
    slug: string;
    starRating: number;
    step: number;
    syncId: number | null;
    totalPeople: number;
    updatedAt: string;
    userId: number;
    website: string | null;
    workingDate: string;
    wubookLcode: null;
    zipCode: string | null;
  }
  interface RoomTypes {
    bedNumber: number;
    bedTypeId: number | null;
    byPerson: boolean;
    createdAt: string;
    days: number | null;
    defaultPrice: number;
    description: string | null;
    discountPercent: number | null;
    endDate: string | null;
    extraBeds: null;
    floorSize: number | null;
    groupCode: number | null;
    hasExtraBed: boolean;
    hasTime: boolean;
    hotelId: number;
    id: number;
    images: string[];
    introductionEn: string | null;
    isOnline: boolean;
    isPriority: number;
    isResRequest: boolean;
    name: string;
    nameEn: string | null;
    number: number;
    occupancy: number;
    occupancyChildren: number;
    peopleNumber: number;
    photos: string;
    priceDayUse: number;
    priceOp: number | null;
    priceTime: number;
    priceTimeCount: number;
    saleQuantity: number | null;
    sales: [];
    shortName: string;
    size: number;
    startDate: string | null;
    syncId: number | null;
    totalPeople: number | null;
    translate: string | null;
    updatedAt: string;
    updatedAtIsPriority: number | null;
    window: number;
  }
  interface Facilities {
    createdAt: string | null;
    facilityCategoryId: number;
    icon: string | null;
    id: number;
    image: string | null;
    isDefault: number;
    isFilter: number;
    isMost: number;
    mobileIcon: string | null;
    name: string;
    nameEn: string | null;
    syncId: number;
    updatedAt: string | null;
  }
  interface Reservations {
    amount: number;
    amountPaid: number;
    arrivalTime: string;
    balance: number;
    beneficiaryAccountNumber: string | null;
    beneficiaryName: string | null;
    cancellationPolicyCloneId: number;
    checkIn: string;
    checkOut: string;
    checkedInAt: string | null;
    checkedOutAt: string | null;
    confirmedAt: string | null;
    createdAt: string;
    day: number;
    discount: number;
    discountType: string;
    dollarRate: string | null;
    exitTime: string;
    externalId: string | null;
    flightdata: string | null;
    groupId: number;
    hotelId: number;
    hotelName: string;
    id: number;
    isTime: boolean;
    notes: string | null;
    number: string;
    numberOfChildren: number;
    numberOfGuests: number;
    partnerCloneId: number | null;
    paymentMethod: string | null;
    postedDate: string;
    priceDollar: string | null;
    ratePlanCloneId: number;
    resReqId: string | null;
    reviewId: string | null;
    roomCloneId: number;
    roomTypeCloneId: number;
    rooms: string;
    socialpayDeeplink: string | null;
    sourceCloneId: number;
    status: string;
    statusAt: string;
    stayNights: number;
    stayType: string;
    syncId: number | null;
    token: string | null;
    updatedAt: string;
    userCloneId: number;
    userId: number | null;
    userdata: string;
    xroomReservationId: number | null;
  }
}
